version: '3.7'
services:
  test_mysql:
    platform: 'linux/amd64'
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306